#!/bin/bash
source ./submodules/bootstrap/logging
set -euo pipefail ; IFS=$'\n\t'

#-----------
# Configurations
#-----------

CADVISOR_LAUNCHER_DIR=${CADVISOR_LAUNCHER_DIR-/var/local/cadvisor}
CADVISOR_DOCKER_LIB=${CADVISOR_DOCKER_LIB-/var/lib/docker}
CADVISOR_PORT=${CADVISOR_PORT-8080}

#-----------
# Install Script
#-----------

notify "Installing cAdvisor"

mkdir -p $CADVISOR_LAUNCHER_DIR

if [[ "$OS" == "redhat" ]] || [[ "$OS" == "centos" ]]; then
  EXTRA_START_FLAGS="--volume=/cgroup:/cgroup"
else
  EXTRA_START_FLAGS=""
fi

printf "%b" "#!/bin/bash
CONTAINER_ID=\`${CADVISOR_LAUNCHER_DIR}/running\`
if [[ \"\$CONTAINER_ID\" == \"\" ]]; then
  echo \"Starting cAdvisor ($CADVISOR_PORT)\"
  docker rm cadvisor > /dev/null 2>&1
  docker run $EXTRA_START_FLAGS \
    --volume=/var/run:/var/run:rw \
    --volume=/sys:/sys:ro \
    --volume=$CADVISOR_DOCKER_LIB:/var/lib/docker:ro \
    --publish=$CADVISOR_PORT:8080 \
    --detach=true \
    --name=cadvisor \
    google/cadvisor:latest 2> /dev/null > ${CADVISOR_LAUNCHER_DIR}/container.pid
else
  echo \"Container cAdvisor  already running, ${CADVISOR_LAUNCHER_DIR}/restart to restart it\"
fi
" > ${CADVISOR_LAUNCHER_DIR}/start

NAME=cAdvisor DIR=$CADVISOR_LAUNCHER_DIR ./submodules/docker/helpers
chmod 755 $CADVISOR_LAUNCHER_DIR/start
