#!/bin/bash
source ./submodules/bootstrap/logging
set -euo pipefail ; IFS=$'\n\t'

#-----------
# Configurations
#-----------

CADVISOR_LAUNCHER_DIR=${CADVISOR_LAUNCHER_DIR-/var/local/cadvisor}

export CADVISOR_DOCKER_LIB=${CADVISOR_DOCKER_LIB-/var/lib/docker}
export CADVISOR_PORT=${CADVISOR_PORT-8080}

#-----------
# Install Script
#-----------

notify "Installing cAdvisor"

mkdir -p $CADVISOR_LAUNCHER_DIR

if [[ "$OS" == "redhat" ]] || [[ "$OS" == "centos" ]]; then
  export EXTRA_START_FLAGS="--volume=/cgroup:/cgroup"
  debug " -- Extra redhat flags: $EXTRA_START_FLAGS"
else
  export EXTRA_START_FLAGS=""
fi

NAME=cadvisor IMAGE_NAME=google/cadvisor:latest DIR=$CADVISOR_LAUNCHER_DIR \
  START=./submodules/cadvisor/files/_start \
  DEBUG=ignore \
  ./submodules/docker/helpers

notify "DONE, Installing cAdvisor"